const mongoose = require("mongoose");

const marriageRegistrationSchema = new mongoose.Schema(
  {
    registrationReference: { type: String, trim: true, default: "" },
    certificateNo: { type: String, trim: true, default: "" },
    applicantIsGroom: { type: Boolean, default: true },
    applicantName: { type: String, required: true, trim: true },
    applicantNic: { type: String, required: true, trim: true },
    applicantMobile: { type: String, required: true, trim: true },
    applicantAddress: { type: String, required: true, trim: true },
    applicantDob: { type: String, trim: true, default: "" },
    groomName: { type: String, required: true, trim: true },
    groomNic: { type: String, required: true, trim: true },
    groomDob: { type: String, required: true, trim: true },
    groomAge: { type: Number, required: true },
    groomOccupation: { type: String, required: true, trim: true },
    groomAddress: { type: String, required: true, trim: true },
    groomReligion: { type: String, required: true, trim: true },
    groomNationality: { type: String, required: true, trim: true },
    groomMaritalStatus: { type: String, required: true, trim: true },
    brideName: { type: String, required: true, trim: true },
    brideNic: { type: String, required: true, trim: true },
    brideDob: { type: String, required: true, trim: true },
    brideAge: { type: Number, required: true },
    brideMobile: { type: String, required: true, trim: true },
    brideOccupation: { type: String, required: true, trim: true },
    brideAddress: { type: String, required: true, trim: true },
    brideReligion: { type: String, required: true, trim: true },
    brideNationality: { type: String, required: true, trim: true },
    brideMaritalStatus: { type: String, required: true, trim: true },
    marriageDate: { type: String, required: true, trim: true },
    marriagePlace: { type: String, required: true, trim: true },
    registrarName: { type: String, required: true, trim: true },
    registrationNumber: { type: String, required: true, trim: true },
    femaleWitnessName: { type: String, required: true, trim: true },
    femaleWitnessNic: { type: String, required: true, trim: true },
    femaleWitnessRelationship: { type: String, required: true, trim: true },
    femaleWitnessAddress: { type: String, required: true, trim: true },
    femaleWitnessPhone: { type: String, required: true, trim: true },
    maleWitnessName: { type: String, required: true, trim: true },
    maleWitnessNic: { type: String, required: true, trim: true },
    maleWitnessRelationship: { type: String, required: true, trim: true },
    maleWitnessAddress: { type: String, required: true, trim: true },
    maleWitnessPhone: { type: String, required: true, trim: true },
    declarationAccepted: { type: Boolean, required: true },
    officerName: { type: String, required: true, trim: true },
    officerServiceNumber: { type: String, required: true, trim: true },
    status: { type: String, default: "sent_to_district_registrar" },
    officer: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    submittedAt: { type: Date, default: Date.now },
  },
  { collection: "MarriageRegistration" }
);

module.exports = mongoose.model("MarriageRegistration", marriageRegistrationSchema);
