export const COLORS = {
  PRIMARY_NAVY: "#0A1F44",
  WHITE: "#FFFFFF",
  BACKGROUND: "#F5F7FA",
  DARK_TEXT: "#1E1E1E",
  LIGHT_BORDER: "#DFE1E4",
  ACCENT_YELLOW: "#F4C430",
  MUTED_TEXT: "#6B7280",
};
